spring:
  datasource:
    url: jdbc:h2:mem:hospitaldb
    driver-class-name: org.h2.Driver
    username: samuel
    password: sami100
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
